find_package(gtsam_catkin QUIET)

if(${gtsam_catkin_FOUND})
  message("GTSAM found.")
  message("GTSAM libraries: ${gtsam_catkin_LIBRARIES}.")
  message("GTSAM headers: ${gtsam_catkin_INCLUDE_DIRS}.")
  add_definitions(-DZE_USE_GTSAM)
  list(APPEND catkin_LIBRARIES  ${gtsam_catkin_LIBRARIES})
  list(APPEND INCLUDE_DIRS ${gtsam_catkin_INCLUDE_DIRS})
else()
  message("GTSAM not found.")
endif()